---
  title: "Explore your data"
---



</br>

<font color='black'>
Responses in your dataset can be visualised in two ways using DinaR: 
</font>

* <font color='black'><b>Statically</b>: one cluster in the large knowledge network can be inspected in a selected condition. One can visually inspect which genes in the network responded in the this particular point in time, condition or treatment.</font>
* <font color='black'><b>Dynamically</b>: one cluster in the knowledge network is visualised through the whole dataset in the order selected in step <a href="Select_experimental_files_for_the_analysis_and_define_the_order.html">Select experimental files...</a> of this Manual.</font>

</br>

### 7.1 Select the cluster to be visualised

<font color='black'>
In order to explore your data you first need to select an individual cluster, which will be presented in different tabs of the application. Clusters have assigned consecutive numbers so any number between 1 and 48 for Arabidopsis and between 1 and 70 for potato Large Knowledge Network will be accepted (default minima and maxima). 

The information on genes and reactions included is given in TABs: <a href="Cluster_Information.html#Nodes.html">Nodes</a>, 
<a href="Cluster_Information.html#Edges">Edges</a>, 
<a href="Cluster_Information.html#subnetwork-MapMan-bins">subnetwork MapMan bins</a> and 
<a href="Cluster_Information.html#Background-cluster">Background cluster</a>.

One can also use TAB <a href="Network_Information.html#Clusters">Clusters</a> or step 7.2 in MENU part to gain insight into specific clusterID.
</font>

</br>

### 7.2 Search for the gene of interest

If one would like to visualise the network surrounding a particular gene of interest one can first search for its position in within the network.

Enter the geneID into the empty window. 
Associated cluster is automatically selected.
Check the column 'GENEclu' within TAB <a href="Cluster_Information.html#Nodes">Nodes</a> to get the information about cluster ID.
The cluster related information is shown as described in previous step (7.1).

<i><b><u>Note</u></b></i>: Cluster selection via geneID has higher priority than Cluster selection via clusterID, hence while proper geneID is written (different from empty string or geneX), selection of cluster by clusterID will not work.

</br>

### 7.3 Filtering of nodes within a cluster

If the cluster is difficult to biologically interpret, you can decide to further filter the nodes that are visualised. Enter the minimal node degree threshold to choose which nodes within the cluster will be shown.

</br>

### 7.4 Select the condition in your dataset to be visualised 
For static visualisation of the selected cluster (see 7.1) one needs to select a particular condition/time-point by entering the order of visualisation number (see the TAB <a href="Experimental_data.html">Experimental data</a> for relation between data files and order of visualisation). One can easily change the selection of the data file using scroll wheel or arrow keys.
</font>
<br>
<br>
For clearer idea see screenshots <a href="Analysis_of_response_in_experimental_data_files.html#Static-frozen">here</a>.
 
